/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppInspecoesIndexRouteImport } from './routes/_app.inspecoes.index'
import { Route as AppChecklistsIndexRouteImport } from './routes/_app.checklists.index'
import { Route as AppInspecoesNovaRouteImport } from './routes/_app.inspecoes.nova'
import { Route as AppInspecoesIdRouteImport } from './routes/_app.inspecoes.$id'
import { Route as AppChecklistsIdRouteImport } from './routes/_app.checklists.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppInspecoesIndexRoute = AppInspecoesIndexRouteImport.update({
  id: '/inspecoes/',
  path: '/inspecoes/',
  getParentRoute: () => AppRoute,
} as any)
const AppChecklistsIndexRoute = AppChecklistsIndexRouteImport.update({
  id: '/checklists/',
  path: '/checklists/',
  getParentRoute: () => AppRoute,
} as any)
const AppInspecoesNovaRoute = AppInspecoesNovaRouteImport.update({
  id: '/inspecoes/nova',
  path: '/inspecoes/nova',
  getParentRoute: () => AppRoute,
} as any)
const AppInspecoesIdRoute = AppInspecoesIdRouteImport.update({
  id: '/inspecoes/$id',
  path: '/inspecoes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppChecklistsIdRoute = AppChecklistsIdRouteImport.update({
  id: '/checklists/$id',
  path: '/checklists/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/checklists/$id': typeof AppChecklistsIdRoute
  '/inspecoes/$id': typeof AppInspecoesIdRoute
  '/inspecoes/nova': typeof AppInspecoesNovaRoute
  '/checklists/': typeof AppChecklistsIndexRoute
  '/inspecoes/': typeof AppInspecoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/checklists/$id': typeof AppChecklistsIdRoute
  '/inspecoes/$id': typeof AppInspecoesIdRoute
  '/inspecoes/nova': typeof AppInspecoesNovaRoute
  '/checklists': typeof AppChecklistsIndexRoute
  '/inspecoes': typeof AppInspecoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/checklists/$id': typeof AppChecklistsIdRoute
  '/_app/inspecoes/$id': typeof AppInspecoesIdRoute
  '/_app/inspecoes/nova': typeof AppInspecoesNovaRoute
  '/_app/checklists/': typeof AppChecklistsIndexRoute
  '/_app/inspecoes/': typeof AppInspecoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/checklists/$id'
    | '/inspecoes/$id'
    | '/inspecoes/nova'
    | '/checklists/'
    | '/inspecoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/checklists/$id'
    | '/inspecoes/$id'
    | '/inspecoes/nova'
    | '/checklists'
    | '/inspecoes'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/checklists/$id'
    | '/_app/inspecoes/$id'
    | '/_app/inspecoes/nova'
    | '/_app/checklists/'
    | '/_app/inspecoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inspecoes/': {
      id: '/_app/inspecoes/'
      path: '/inspecoes'
      fullPath: '/inspecoes/'
      preLoaderRoute: typeof AppInspecoesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checklists/': {
      id: '/_app/checklists/'
      path: '/checklists'
      fullPath: '/checklists/'
      preLoaderRoute: typeof AppChecklistsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inspecoes/nova': {
      id: '/_app/inspecoes/nova'
      path: '/inspecoes/nova'
      fullPath: '/inspecoes/nova'
      preLoaderRoute: typeof AppInspecoesNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inspecoes/$id': {
      id: '/_app/inspecoes/$id'
      path: '/inspecoes/$id'
      fullPath: '/inspecoes/$id'
      preLoaderRoute: typeof AppInspecoesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checklists/$id': {
      id: '/_app/checklists/$id'
      path: '/checklists/$id'
      fullPath: '/checklists/$id'
      preLoaderRoute: typeof AppChecklistsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppChecklistsIdRoute: typeof AppChecklistsIdRoute
  AppInspecoesIdRoute: typeof AppInspecoesIdRoute
  AppInspecoesNovaRoute: typeof AppInspecoesNovaRoute
  AppChecklistsIndexRoute: typeof AppChecklistsIndexRoute
  AppInspecoesIndexRoute: typeof AppInspecoesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppChecklistsIdRoute: AppChecklistsIdRoute,
  AppInspecoesIdRoute: AppInspecoesIdRoute,
  AppInspecoesNovaRoute: AppInspecoesNovaRoute,
  AppChecklistsIndexRoute: AppChecklistsIndexRoute,
  AppInspecoesIndexRoute: AppInspecoesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
